version: '3.5'

services:
  nuxt-app:
    build: .
    image: nuxt-app
    container_name: nuxt-app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: ['npm', 'run', 'dev']
